version: "3"

services:
  web:
    image: vue-docker-image
    container_name: vue-docker
    build: ./nuxt-todo
    ports:
      - 4000:3000
  storybook:
    image: vue-docker-image
    container_name: storybook-docker
    build: ./nuxt-todo
    expose:
      - "5000"
    ports:
      - "5000:6006"
    command: "yarn storybook"
