name: Deploy
defaults:
  run:
    working-directory: nuxt-todo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy files to AWS s3
        run: |
          aws s3 sync ./dist s3://nuxt-todo
