name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: cd nuxt-todo && yarn
      - name: Build
        run: cd nuxt-todo && yarn generate
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy files to AWS s3
        run: |
          aws s3 sync ./nuxt-todo/dist s3://nuxt-todo
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/index.html"
          AWS_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
